version: 1
default_environment: dev
project_id: f03cdf0f-d30c-4506-9515-a278dbcfb5f1
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: meltanolabs-tap-postgres
    config:
      database: postgres
      filter_schemas:
      - public
      host: aws-1-ap-southeast-1.pooler.supabase.com
      port: 5432
      user: postgres.ioavqbkdsmlzxubamboc
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git
    config:
      batch_size: 104857600
      credentials_path: 
        /Users/jefflee/SCTP/5m-data-2.6-data-pipelines-orchestration/meltano-ingestion/my-sctp-project-31844-e80d83cfc65a.json
      dataset: resale
      denormalized: true
      flattening_enabled: true
      flattening_max_depth: 1
      method: batch_job
      project: my-sctp-project-31844
