resale_flat:
  outputs:
    dev:
      dataset: resale
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/jefflee/SCTP/5m-data-2.6-data-pipelines-orchestration/meltano-ingestion/my-sctp-project-31844-e80d83cfc65a.json
      location: US
      method: service-account
      priority: interactive
      project: my-sctp-project-31844
      threads: 1
      type: bigquery
  target: dev